// Generated by CoffeeScript 1.11.1
var Gesture;

Gesture = require("./Gesture");

Gesture.Responder = require("./Responder");

Gesture.ResponderList = require("./ResponderList");

module.exports = Gesture;
