// Generated by CoffeeScript 1.12.4
var Gesture;

Gesture = require("./Gesture");

Gesture.Responder = require("./Responder");

Gesture.ResponderList = require("./ResponderList");

module.exports = Gesture;
